@Library('devops-pipeline-library') _

pipeline {

    agent any

    environment {
        APP_NAME      = 'ecommerce-api'
        APP_DIR       = 'app-monolith'
        APP_VERSION   = '1.0.0'

        AWS_REGION    = 'us-east-1'
        ECR_REGISTRY  = '962800862954.dkr.ecr.us-east-1.amazonaws.com'
        ECR_REPO      = "${ECR_REGISTRY}/ecommerce-api"
        IMAGE_TAG     = "${APP_VERSION}-${BUILD_NUMBER}"

        NEXUS_URL     = 'http://32.193.251.152:8081/repository/maven-releases'
        SONAR_URL     = 'http://32.193.251.152:9000'

        HELM_CHART    = 'helm-monolith'
        K8S_NAMESPACE = 'ecommerce'
        EKS_CLUSTER   = 'enterprise-eks-us-east-1'
    }

    tools {
        maven 'Maven-3.9'
        jdk 'JDK-17'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 60, unit: 'MINUTES')
        timestamps()
    }

    stages {

        stage('Checkout') {
            steps {
                checkoutCode(
                    branch: 'main',
                    repoUrl: 'https://github.com/gani1123/Enterprise-devops-platform-ecommerce-eks.git',
                    credentialsId: 'github-cred'
                )
            }
        }

        stage('Build WAR') {
            steps {
                buildWar(
                 
                )
            }
        }

        stage('Publish WAR to Nexus') {
    steps {
        nexusUpload(
           
        )
    }
}

        stage('SonarQube Scan') {
            steps {
                sonarScan(
                    appDir: APP_DIR,
                    sonarUrl: SONAR_URL,
                    projectKey: APP_NAME,
                    projectName: 'E-commerce API'
                )
            }
        }

        stage('Docker Build') {
            steps {
                dockerBuild(
                    appDir: APP_DIR,
                    ecrRepo: ECR_REPO,
                    imageTag: IMAGE_TAG
                )
            }
        }

        stage('Trivy Scan') {
            steps {
                trivyScan(
                    ecrRepo: ECR_REPO,
                    imageTag: IMAGE_TAG
                )
            }
        }

        stage('Push Image to ECR') {
            steps {
                dockerPush(
            
                )
            }
        }

        stage('Deploy to EKS') {
            steps {
                deployEKS(
                    awsRegion: AWS_REGION,
                    eksCluster: EKS_CLUSTER,
                    namespace: K8S_NAMESPACE,
                    helmChart: HELM_CHART,
                    appName: APP_NAME,
                    appVersion: APP_VERSION,
                    ecrRepo: ECR_REPO,
                    imageTag: IMAGE_TAG
                )
            }
        }
    }

    post {

        success {
            echo "✅ ${APP_NAME}:${IMAGE_TAG} deployed successfully."
        }

        failure {
            echo "❌ Pipeline failed."
        }

        always {
            cleanup(
                ecrRepo: ECR_REPO,
                imageTag: IMAGE_TAG
            )
        }
    }
}
